version: "3"

# 声明一个名为network的networks,subnet为network的子网地址,默认网关是177.7.0.1
networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: '177.7.0.0/16'

# 设置mysql，redis持久化保存
#volumes:
#  mysql:
#  redis:

services:
  ba-web:
    build:
      context: ../../web
      dockerfile: ./Dockerfile
    container_name: ba-web
    image: ba-web
    restart: always
    ports:
      - '8000:8000'
#    depends_on:
#      - ba-server
    command: [ 'nginx-debug', '-g', 'daemon off;' ]
    networks:
      network:
        ipv4_address: 177.7.0.11

  ba-server:
    build:
      context: ../../server
      dockerfile: ./Dockerfile
    image: ba-server
    container_name: ba-server
    restart: always
    volumes:
      - ../../server/config.docker.yaml:/app/config.yaml
    ports:
      - '8600:8600'
#    depends_on:
#      - mysql
#      - redis
#    links:
#      - mysql
#      - redis
    networks:
      network:
        ipv4_address: 177.7.0.12

#  mysql:
#    image: mysql:8.0.21       # 如果您是 arm64 架构：如 MacOS 的 M1，请修改镜像为 image: mysql/mysql-server:8.0.21
#    container_name: ba-mysql
#    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci #设置utf8字符集
#    restart: always
#    ports:
#      - "23306:3306"  # host物理直接映射端口为13306
#    environment:
##      MYSQL_DATABASE: 'qmPlus' # 初始化启动时要创建的数据库的名称
#      MYSQL_USER: 'root'
#      MYSQL_PASSWORD: 'Ab@123456!'
#    volumes:
#      - mysql:/var/lib/mysql
#    networks:
#      network:
#        ipv4_address: 177.7.0.13
#
#  redis:
#    image: redis:6.0.6
#    container_name: ba-redis # 容器名
#    restart: always
#    ports:
#      - '6379:6379'
#    volumes:
#      - redis:/data
#    networks:
#      network:
#        ipv4_address: 177.7.0.14
